#pragma once

#include "GlobalVariables.C"

#include "DisplayOn.C"
#include "G4Setup_EICDetector.C"
#include "G4_Bbc.C"
#include "G4_CaloTrigger.C"
#include "G4_DSTReader_EICDetector.C"
#include "G4_FwdJets.C"
#include "G4_Global.C"
#include "G4_HIJetReco.C"
#include "G4_Jets.C"

#include <fun4all/Fun4AllDstInputManager.h>
#include <fun4all/Fun4AllDstOutputManager.h>
#include <fun4all/Fun4AllDummyInputManager.h>
#include <fun4all/Fun4AllInputManager.h>
#include <fun4all/Fun4AllNoSyncDstInputManager.h>
#include <fun4all/Fun4AllOutputManager.h>
#include <fun4all/Fun4AllServer.h>
#include <fun4all/SubsysReco.h>
#include <g4detectors/PHG4DetectorSubsystem.h>
#include <g4eval/PHG4DSTReader.h>
#include <g4main/HepMCNodeReader.h>
#include <g4main/PHG4ParticleGenerator.h>
#include <g4main/PHG4ParticleGeneratorBase.h>
#include <g4main/PHG4ParticleGeneratorVectorMeson.h>
#include <g4main/PHG4ParticleGun.h>
#include <g4main/PHG4SimpleEventGenerator.h>
#include <g4main/ReadEICFiles.h>
#include <phhepmc/Fun4AllHepMCInputManager.h>
#include <phool/recoConsts.h>
#include <phpythia6/PHPythia6.h>
#include <phpythia8/PHPythia8.h>
#include <phsartre/PHSartre.h>
#include <phsartre/PHSartreParticleTrigger.h>

R__LOAD_LIBRARY(libfun4all.so)
R__LOAD_LIBRARY(libg4testbench.so)
R__LOAD_LIBRARY(libPHPythia6.so)
R__LOAD_LIBRARY(libPHPythia8.so)
R__LOAD_LIBRARY(libPHSartre.so)

int Fun4All_G4_EICDetector(
    const int nEvents = 1,
    const char *inputFile = "/sphenix/data/data02/review_2017-08-02/single_particle/spacal2d/fieldmap/G4Hits_sPHENIX_e-_eta0_8GeV-0002.root",
    const char *outputFile = "G4EICDetector.root")
{
  //===============
  // Input options
  //===============

  // Either:
  // read previously generated g4-hits files, in this case it opens a DST and skips
  // the simulations step completely. The G4Setup macro is only loaded to get information
  // about the number of layers used for the cell reco code
  //
  // In case reading production output, please double check your G4Setup_sPHENIX.C and G4_*.C consistent with those in the production macro folder
  // E.g. /sphenix/sim//sim01/production/2016-07-21/single_particle/spacal2d/
  const bool readhits = false;
  // Or:
  // read files in HepMC format (typically output from event generators like hijing or pythia)
  const bool readhepmc = false;  // read HepMC files
  // Or:
  // read files in EICTree format generated by eicsmear package
  const bool readeictree = false;
  // Or:
  // Use Pythia 8
  const bool runpythia8 = false;
  // Or:
  // Use Pythia 6
  const bool runpythia6 = false;
  // Or:
  // Use HEPGen
  const bool runhepgen = false;
  // Or:
  // Use Sartre
  const bool runsartre = false;

  // Besides the above flags. One can further choose to further put in following particles in Geant4 simulation
  // Use multi-particle generator (PHG4SimpleEventGenerator), see the code block below to choose particle species and kinematics
  const bool particles = true && !readhits;
  // or gun/ very simple single particle gun generator
  const bool usegun = false && !readhits;
  // Throw single Upsilons, may be embedded in Hijing by setting readhepmc flag also  (note, careful to set Z vertex equal to Hijing events)
  const bool upsilons = false && !readhits;

  // Write the DST
  Enable::DSTOUT = false;
  // Compress DST files
  Enable::DSTOUT_COMPRESS = false;
  //Option to convert DST to human command readable TTree for quick poke around the outputs
  const bool do_DSTReader = false;

  //======================
  // What to run
  //======================

  // sPHENIX barrel
  bool do_bbc = true;

  // whether to simulate the Be section of the beam pipe
  Enable::PIPE = true;
  // EIC beam pipe extension beyond the Be-section can be turned on with use_forward_pipes = true in G4_Pipe_EIC.C

  Enable::EGEM = true;
  Enable::FGEM = true;
  Enable::MVTX = true;
  Enable::TPC = true;
  Enable::TRACKING = true;
  bool do_tracking_cell = Enable::TRACKING && true;
  bool do_tracking_track = do_tracking_cell && true;
  bool do_tracking_eval = do_tracking_track && true;
  bool do_vertex_finding = false;  // this option exclude vertex in the track fitting and use RAVE to reconstruct primary and 2ndary vertexes

  Enable::CEMC = true;
  bool do_cemc_cell = Enable::CEMC && true;
  bool do_cemc_twr = do_cemc_cell && true;
  bool do_cemc_cluster = do_cemc_twr && true;
  bool do_cemc_eval = do_cemc_cluster && true;

  Enable::HCALIN = true;
  bool do_hcalin_cell = Enable::HCALIN && true;
  bool do_hcalin_twr = do_hcalin_cell && true;
  bool do_hcalin_cluster = do_hcalin_twr && true;
  bool do_hcalin_eval = do_hcalin_cluster && true;

  Enable::MAGNET = true;

  Enable::HCALOUT = true;
  bool do_hcalout_cell = Enable::HCALOUT && true;
  bool do_hcalout_twr = do_hcalout_cell && true;
  bool do_hcalout_cluster = do_hcalout_twr && true;
  bool do_hcalout_eval = do_hcalout_cluster && true;

  // EICDetector geometry - barrel
  Enable::DIRC = true;

  // EICDetector geometry - 'hadron' direction
  Enable::RICH = true;
  Enable::AEROGEL = true;

  Enable::FEMC = true;
  bool do_FEMC_cell = Enable::FEMC && true;
  bool do_FEMC_twr = do_FEMC_cell && true;
  bool do_FEMC_cluster = do_FEMC_twr && true;
  bool do_FEMC_eval = do_FEMC_cluster && true;

  Enable::FHCAL = true;
  bool do_FHCAL_cell = Enable::FHCAL && true;
  bool do_FHCAL_twr = do_FHCAL_cell && true;
  bool do_FHCAL_cluster = do_FHCAL_twr && true;
  bool do_FHCAL_eval = do_FHCAL_cluster && true;

  // EICDetector geometry - 'electron' direction
  Enable::EEMC = true;
  bool do_EEMC_cell = Enable::EEMC && true;
  bool do_EEMC_twr = do_EEMC_cell && true;
  bool do_EEMC_cluster = do_EEMC_twr && true;
  bool do_EEMC_eval = do_EEMC_cluster && true;

  Enable::PLUGDOOR = true;

  // Other options
  bool do_global = true;
  bool do_global_fastsim = true;

  bool do_calotrigger = false && do_cemc_twr && do_hcalin_twr && do_hcalout_twr;

  // Select only one jet reconstruction- they currently use the same
  // output collections on the node tree!
  bool do_jet_reco = false;
  bool do_jet_eval = do_jet_reco && true;

  bool do_fwd_jet_reco = false;
  bool do_fwd_jet_eval = do_fwd_jet_reco && true;

  // HI Jet Reco for jet simulations in Au+Au (default is false for
  // single particle / p+p simulations, or for Au+Au simulations which
  // don't care about jets)
  bool do_HIjetreco = false && do_jet_reco && do_cemc_twr && do_hcalin_twr && do_hcalout_twr;

  // new settings using Enable namespace in GlobalVariables.C
  Enable::BLACKHOLE = true;
  BlackHoleGeometry::visible = true;

  //---------------
  // Load libraries
  //---------------

  // establish the geometry and reconstruction setup
  G4Init();

  int absorberactive = 0;  // set to 1 to make all absorbers active volumes
  //  const string magfield = "1.5"; // alternatively to specify a constant magnetic field, give a float number, which will be translated to solenoidal field in T, if string use as fieldmap name (including path)
  const string magfield = string(getenv("CALIBRATIONROOT")) + string("/Field/Map/sPHENIX.2d.root");  // default map from the calibration database
  const float magfield_rescale = -1.4 / 1.5;                                                         // scale the map to a 1.4 T field. Reverse field sign to get around a bug in RAVE

  //---------------
  // Fun4All server
  //---------------

  Fun4AllServer *se = Fun4AllServer::instance();
  // se->Verbosity(01); // uncomment for batch production running with minimal output messages
  // se->Verbosity(Fun4AllServer::VERBOSITY_SOME); // uncomment for some info for interactive running

  // just if we set some flags somewhere in this macro
  recoConsts *rc = recoConsts::instance();
  // By default every random number generator uses
  // PHRandomSeed() which reads /dev/urandom to get its seed
  // if the RANDOMSEED flag is set its value is taken as seed
  // You can either set this to a random value using PHRandomSeed()
  // which will make all seeds identical (not sure what the point of
  // this would be:
  //  rc->set_IntFlag("RANDOMSEED",PHRandomSeed());
  // or set it to a fixed value so you can debug your code
//  rc->set_IntFlag("RANDOMSEED", 12345);

  //-----------------
  // Event generation
  //-----------------

  if (readhits)
  {
    // Get the hits from a file
    // The input manager is declared later
  }
  else if (readhepmc)
  {
    // action is performed in later stage at the input manager level
  }
  else if (readeictree)
  {
    // this module is needed to read the EICTree style records into our G4 sims
    ReadEICFiles *eicr = new ReadEICFiles();
    eicr->OpenInputFile(inputFile);

    se->registerSubsystem(eicr);
  }
  else if (runpythia8)
  {
    PHPythia8 *pythia8 = new PHPythia8();
    // see coresoftware/generators/PHPythia8 for example config
    pythia8->set_config_file("phpythia8.cfg");
    se->registerSubsystem(pythia8);
  }
  else if (runpythia6)
  {
    PHPythia6 *pythia6 = new PHPythia6();
    // see coresoftware/generators/PHPythia6 for example config
    pythia6->set_config_file("phpythia6_ep.cfg");
    se->registerSubsystem(pythia6);
  }
  /*
  else if (runhepgen)
    {
      gSystem->Load("libsHEPGen.so");

      sHEPGen *hepgen = new sHEPGen();
      // see HEPGen source directory/share/vggdata for required .dat files
      // see HEPGen source directory/share/datacards for required datacard files
      hepgen->set_datacard_file("hepgen_dvcs.data");
      hepgen->set_momentum_electron(-20);
      hepgen->set_momentum_hadron(250);
      se->registerSubsystem(hepgen);
    }
*/
  else if (runsartre)
  {
    // see coresoftware/generators/PHSartre/README for setup instructions
    // before running:
    // setenv SARTRE_DIR /opt/sphenix/core/sartre-1.20_root-5.34.36

    PHSartre *mysartre = new PHSartre();
    // see coresoftware/generators/PHSartre for example config
    mysartre->set_config_file("sartre.cfg");

    // particle trigger to enhance forward J/Psi -> ee
    PHSartreParticleTrigger *pTrig = new PHSartreParticleTrigger("MySartreTrigger");
    pTrig->AddParticles(-11);
    //pTrig->SetEtaHighLow(4.0,1.4);
    pTrig->SetEtaHighLow(1.0, -1.1);  // central arm
    pTrig->PrintConfig();
    mysartre->register_trigger((PHSartreGenTrigger *) pTrig);
    se->registerSubsystem(mysartre);
  }

  // If "readhepMC" is also set, the particles will be embedded in Hijing events
  if (particles)
  {
    // toss low multiplicity dummy events
    PHG4SimpleEventGenerator *gen = new PHG4SimpleEventGenerator();
    gen->add_particles("pi-", 1);  // mu+,e+,proton,pi+,Upsilon
    //gen->add_particles("pi+",100); // 100 pion option

    if (readhepmc)
    {
      gen->set_reuse_existing_vertex(true);
      gen->set_existing_vertex_offset_vector(0.0, 0.0, 0.0);
    }
    else
    {
      gen->set_vertex_distribution_function(PHG4SimpleEventGenerator::Uniform,
                                            PHG4SimpleEventGenerator::Uniform,
                                            PHG4SimpleEventGenerator::Uniform);
      gen->set_vertex_distribution_mean(0.0, 0.0, 0.0);
      gen->set_vertex_distribution_width(0.0, 0.0, 0.0);
    }
    gen->set_vertex_size_function(PHG4SimpleEventGenerator::Uniform);
    gen->set_vertex_size_parameters(0.0, 0.0);
    gen->set_eta_range(-3, 3);
    gen->set_phi_range(-1.0 * TMath::Pi(), 1.0 * TMath::Pi());
    //gen->set_pt_range(0.1, 50.0);
    gen->set_pt_range(0.1, 20.0);
    gen->Embed(1);
    gen->Verbosity(0);

    se->registerSubsystem(gen);
  }
  if (usegun)
  {
    // PHG4ParticleGun *gun = new PHG4ParticleGun();
    // gun->set_name("anti_proton");
    // gun->set_name("geantino");
    // gun->set_vtx(0, 0, 0);
    // gun->set_mom(10, 0, 0.01);
    // gun->AddParticle("geantino",1.7776,-0.4335,0.);
    // gun->AddParticle("geantino",1.7709,-0.4598,0.);
    // gun->AddParticle("geantino",2.5621,0.60964,0.);
    // gun->AddParticle("geantino",1.8121,0.253,0.);
    // se->registerSubsystem(gun);
    PHG4ParticleGenerator *pgen = new PHG4ParticleGenerator();
    pgen->set_name("mu-");
    pgen->set_z_range(0, 0);
    pgen->set_eta_range(-4.0, 0.0);
    pgen->set_mom_range(30, 30);
    pgen->set_phi_range(-1.0 * TMath::Pi(), 1.0 * TMath::Pi());
    se->registerSubsystem(pgen);
  }

  // If "readhepMC" is also set, the Upsilons will be embedded in Hijing events, if 'particles" is set, the Upsilons will be embedded in whatever particles are thrown
  if (upsilons)
  {
    // run upsilons for momentum, dca performance, alone or embedded in Hijing

    PHG4ParticleGeneratorVectorMeson *vgen = new PHG4ParticleGeneratorVectorMeson();
    vgen->add_decay_particles("e+", "e-", 0);  // i = decay id
    // event vertex
    if (readhepmc || particles)
    {
      vgen->set_reuse_existing_vertex(true);
    }

    // Note: this rapidity range completely fills the acceptance of eta = +/- 1 unit
    vgen->set_rapidity_range(-1.0, +1.0);
    vgen->set_pt_range(0.0, 10.0);

    int istate = 1;

    if (istate == 1)
    {
      // Upsilon(1S)
      vgen->set_mass(9.46);
      vgen->set_width(54.02e-6);
    }
    else if (istate == 2)
    {
      // Upsilon(2S)
      vgen->set_mass(10.0233);
      vgen->set_width(31.98e-6);
    }
    else
    {
      // Upsilon(3S)
      vgen->set_mass(10.3552);
      vgen->set_width(20.32e-6);
    }

    vgen->Verbosity(0);
    vgen->Embed(2);
    se->registerSubsystem(vgen);

    cout << "Upsilon generator for istate = " << istate << " created and registered " << endl;
  }

  if (!readhits)
  {
    //---------------------
    // Detector description
    //---------------------

    G4Setup(absorberactive, magfield, EDecayType::kAll,
            magfield_rescale);
  }

  //---------
  // BBC Reco
  //---------

  if (do_bbc)
  {
    BbcInit();
    Bbc_Reco();
  }

  //------------------
  // Detector Division
  //------------------

  if (do_tracking_cell) Svtx_Cells();

  if (do_cemc_cell) CEMC_Cells();

  if (do_hcalin_cell) HCALInner_Cells();

  if (do_hcalout_cell) HCALOuter_Cells();

  if (do_FEMC_cell) FEMC_Cells();

  if (do_FHCAL_cell) FHCAL_Cells();

  if (do_EEMC_cell) EEMC_Cells();

  //-----------------------------
  // CEMC towering and clustering
  //-----------------------------

  if (do_cemc_twr) CEMC_Towers();
  if (do_cemc_cluster) CEMC_Clusters();

  //-----------------------------
  // HCAL towering and clustering
  //-----------------------------

  if (do_hcalin_twr) HCALInner_Towers();
  if (do_hcalin_cluster) HCALInner_Clusters();

  if (do_hcalout_twr) HCALOuter_Towers();
  if (do_hcalout_cluster) HCALOuter_Clusters();

  //-----------------------------
  // e, h direction Calorimeter  towering and clustering
  //-----------------------------

  if (do_FEMC_twr) FEMC_Towers();
  if (do_FEMC_cluster) FEMC_Clusters();

  if (do_FHCAL_twr) FHCAL_Towers();
  if (do_FHCAL_cluster) FHCAL_Clusters();

  if (do_EEMC_twr) EEMC_Towers();
  if (do_EEMC_cluster) EEMC_Clusters();

  if (Enable::DSTOUT_COMPRESS) ShowerCompress();

  //--------------
  // SVTX tracking
  //--------------

  if (do_tracking_track) Tracking_Reco(0, do_vertex_finding);

  //-----------------
  // Global Vertexing
  //-----------------

  if (do_global)
  {
    Global_Reco();
  }

  else if (do_global_fastsim)
  {
    Global_FastSim();
  }

  //-----------------
  // Calo Trigger Simulation
  //-----------------

  if (do_calotrigger)
  {
    CaloTrigger_Sim();
  }

  //---------
  // Jet reco
  //---------

  if (do_jet_reco)
  {
    Jet_Reco();
  }

  if (do_HIjetreco)
  {
    HIJetReco();
  }

  if (do_fwd_jet_reco)
  {
    Jet_FwdReco();
  }

  //----------------------
  // Simulation evaluation
  //----------------------
  if (do_tracking_eval) Tracking_Eval(string(outputFile) + "_g4tracking_eval.root");

  if (do_cemc_eval) CEMC_Eval(string(outputFile) + "_g4cemc_eval.root");

  if (do_hcalin_eval) HCALInner_Eval(string(outputFile) + "_g4hcalin_eval.root");

  if (do_hcalout_eval) HCALOuter_Eval(string(outputFile) + "_g4hcalout_eval.root");

  if (do_FEMC_eval) FEMC_Eval(string(outputFile) + "_g4femc_eval.root");

  if (do_FHCAL_eval) FHCAL_Eval(string(outputFile) + "_g4fhcal_eval.root");

  if (do_EEMC_eval) EEMC_Eval(string(outputFile) + "_g4eemc_eval.root");

  if (do_jet_eval) Jet_Eval(string(outputFile) + "_g4jet_eval.root");

  if (do_fwd_jet_eval) Jet_FwdEval(string(outputFile) + "_g4fwdjet_eval.root");

  //--------------
  // IO management
  //--------------

  if (readhits)
  {
    // Hits file
    Fun4AllInputManager *hitsin = new Fun4AllDstInputManager("DSTin");
    hitsin->fileopen(inputFile);
    se->registerInputManager(hitsin);
  }
  if (readhepmc)
  {
    Fun4AllInputManager *in = new Fun4AllHepMCInputManager("DSTIN");
    se->registerInputManager(in);
    se->fileopen(in->Name().c_str(), inputFile);
  }
  else
  {
    // for single particle generators we just need something which drives
    // the event loop, the Dummy Input Mgr does just that
    Fun4AllInputManager *in = new Fun4AllDummyInputManager("JADE");
    se->registerInputManager(in);
  }

  if (do_DSTReader)
  {
    //Convert DST to human command readable TTree for quick poke around the outputs
    G4DSTreader_EICDetector(outputFile,  //
                            /*int*/ absorberactive,
                            /*bool*/ Enable::TRACKING,
                            /*bool*/ Enable::CEMC,
                            /*bool*/ Enable::HCALIN,
                            /*bool*/ Enable::MAGNET,
                            /*bool*/ Enable::HCALOUT,
                            /*bool*/ do_cemc_twr,
                            /*bool*/ do_hcalin_twr,
                            /*bool*/ do_hcalout_twr,
                            /*bool*/ Enable::FHCAL,
                            /*bool*/ do_FHCAL_twr,
                            /*bool*/ Enable::FEMC,
                            /*bool*/ do_FEMC_twr,
                            /*bool*/ Enable::EEMC,
                            /*bool*/ do_EEMC_twr);
  }

  if(Enable::DSTOUT)
  {
    Fun4AllDstOutputManager *out = new Fun4AllDstOutputManager("DSTOUT", outputFile);
    if (Enable::DSTOUT_COMPRESS) DstCompress(out);
    se->registerOutputManager(out);
  }

  //-----------------
  // Event processing
  //-----------------
  if (nEvents < 0)
  {
    return 0;
  }
  // if we run the particle generator and use 0 it'll run forever
  if (nEvents == 0 && !readhits && !readhepmc)
  {
    cout << "using 0 for number of events is a bad idea when using particle generators" << endl;
    cout << "it will run forever, so I just return without running anything" << endl;
    return 0;
  }

  se->run(nEvents);

  //-----
  // Exit
  //-----

  se->End();
  std::cout << "All done" << std::endl;
  delete se;
  gSystem->Exit(0);
  return 0;
}

// This function is only used to test if we can load this as root6 macro
// without running into unresolved libraries and include files
void RunFFALoadTest() {}
