Universe           = vanilla
getenv             = True
Initialdir         = /direct/phenix+u/workarea/hemmick/code.GITFIXED/macros/calibrations/tpc/gemcurrents
Executable         = $(Initialdir)/ConditionsForOneRun.sh
Output             = $(Initialdir)/out/Conditions_$(process).out
Error              = $(Initialdir)/err/Conditions_$(process).err
Log                = $(Initialdir)/log/Conditions_$(process).log
PeriodicHold       = (NumJobStarts>=1 && JobStatus == 1)
request_cpus       = 1
request_memory     = 512MB
Priority           = 20
job_lease_duration = 3600
Arguments          = $(process)
Queue 3413
